2024-05-20 04:14:47,359 INFO    MainThread:1412160 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-20 04:14:47,359 INFO    MainThread:1412160 [wandb_setup.py:_flush():76] Configure stats pid to 1412160
2024-05-20 04:14:47,359 INFO    MainThread:1412160 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-05-20 04:14:47,360 INFO    MainThread:1412160 [wandb_setup.py:_flush():76] Loading settings from /home/ayhan/gflownet-rl/hypergrid/wandb/settings
2024-05-20 04:14:47,360 INFO    MainThread:1412160 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-20 04:14:47,360 INFO    MainThread:1412160 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-20 04:14:47,360 INFO    MainThread:1412160 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'hypergrid/run_hypergrid_exp.py', 'program_abspath': '/home/ayhan/gflownet-rl/hypergrid/run_hypergrid_exp.py', 'program': '/home/ayhan/gflownet-rl/hypergrid/run_hypergrid_exp.py'}
2024-05-20 04:14:47,360 INFO    MainThread:1412160 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-20 04:14:47,360 INFO    MainThread:1412160 [wandb_init.py:_log_setup():520] Logging user logs to /home/ayhan/gflownet-rl/hypergrid/wandb/run-20240520_041447-eb5nmbeo/logs/debug.log
2024-05-20 04:14:47,360 INFO    MainThread:1412160 [wandb_init.py:_log_setup():521] Logging internal logs to /home/ayhan/gflownet-rl/hypergrid/wandb/run-20240520_041447-eb5nmbeo/logs/debug-internal.log
2024-05-20 04:14:47,360 INFO    MainThread:1412160 [wandb_init.py:init():560] calling init triggers
2024-05-20 04:14:47,360 INFO    MainThread:1412160 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-20 04:14:47,361 INFO    MainThread:1412160 [wandb_init.py:init():610] starting backend
2024-05-20 04:14:47,361 INFO    MainThread:1412160 [wandb_init.py:init():614] setting up manager
2024-05-20 04:14:47,363 INFO    MainThread:1412160 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-20 04:14:47,365 INFO    MainThread:1412160 [wandb_init.py:init():622] backend started and connected
2024-05-20 04:14:47,368 INFO    MainThread:1412160 [wandb_init.py:init():711] updated telemetry
2024-05-20 04:14:47,375 INFO    MainThread:1412160 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-20 04:14:47,939 INFO    MainThread:1412160 [wandb_run.py:_on_init():2396] communicating current version
2024-05-20 04:14:48,052 INFO    MainThread:1412160 [wandb_run.py:_on_init():2405] got version response 
2024-05-20 04:14:48,052 INFO    MainThread:1412160 [wandb_init.py:init():795] starting run threads in backend
2024-05-20 04:14:49,896 WARNING MainThread:1412160 [wandb_init.py:init():1168] interrupted
Traceback (most recent call last):
  File "/root/miniconda3/envs/gflownet-rl/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/root/miniconda3/envs/gflownet-rl/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/root/miniconda3/envs/gflownet-rl/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/root/miniconda3/envs/gflownet-rl/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/root/miniconda3/envs/gflownet-rl/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/root/miniconda3/envs/gflownet-rl/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/root/miniconda3/envs/gflownet-rl/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-05-20 04:14:53,825 WARNING MsgRouterThr:1412160 [router.py:message_loop():77] message_loop has been closed
